name: Deploy Biowood Prod
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependency
        run: npm install

      - name: Build Biowood ERP production website
        run: CI=false npm run build:prod

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        if: github.event_name == 'push'
        run: aws s3 sync build s3://${{ secrets.AWS_PROD_BUCKET_NAME }} --delete

      - name: Invalidate Cloudfront
        if: github.event_name == 'push'
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
